apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: immich
      defaultBucket: immich
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    uid: ef8gkv3lzo0lcc
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: af8r4ktgyqoe8b
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000

  - name: Proxmox-InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: immich
      defaultBucket: proxmox
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    uid: proxmox-influxdb
    isDefault: false
    editable: true
